### PR TITLE
Add method: postJson

### PR DESCRIPTION
**Pull request by brendonparker**
It would be nice to be able to make a post request with content type of application/json and to send a json object.

Added a new post method to `cordovaHTTP` called `postJson` which behaves the same as `cordovaHTTP.post` but will send the data as application/json instead of as `application/x-www-form-urlencoded`

Code use looks like this:

``` javascript
var dto = {
    description: 'sending a plain old javascript object',
    child: {
        foo: 'bar',
    }
};

cordovaHTTP.postJson('https://some-server/api/', dto, { }, function(response) {
        // prints 200
        console.log(response.status);
        try {
            // response.data has already been parsed
            //response.data = JSON.parse(response.data);

            // prints test
            console.log(response.data.message);
        } catch(e) {
            console.error('JSON parsing error');
        }
    }, function(response) {
        // prints 403
        console.log(response.status);

        //prints Permission denied 
        console.log(response.error);
    });
```

### CODE REVIEW

**Comment by Remicek** [comment]
@brendonparker I've been trying to use your fork with this example, but i get error
(while debuggin in file cordova.js),

line 940:
var msgs = nativeApiProvider.get().exec(bridgeSecret, service, action, callbackId, argsJson);

and msgs have the value of = "42 F08 CordovaHttpPlugin600273986 sJSON error" 

it doesnt tell me much where is the error here, do you have some idea?

**Comment by brendonparker** [comment]
@Remicek can you send a snippet of your client-side javascript that is trying to send JSON?

**Comment by Remicek** [comment]
Method without Pinning 

```
this.POST_WITHOUT_PINNING = function( inData, methodName, callBack_Success, callBack_Error ){
		
			generateNewObject( inData );
			getMobileNumber();
			
			var myURL = connectionSettingController.getConnection_URL();
			myURL = myURL + "/" + methodName.replace("/","");
			//console.log(" ========== post_B ========== ");
			//console.log(" = URL : " + myURL + " / " + methodName);
			
			$.ajax({
				url: myURL,
				type: "POST",
				dataType: "json",
				data: obData,
				beforeSend: function(xhr){
					xhr.setRequestHeader( "Content-Type", "application/json" );
					xhr.setRequestHeader( "Accept", "application/json" );
				},
				success: function(data, result, response){ 
					callBack_Success( data );
				},
				error: function(res){ 
					callBack_Error(res);
				},
				
			});
	}
```

Method with pinning PostJson

```
this.POST_PINNING = function( inData, methodName, callBack_Success, callBack_Error ){
		
		generateNewObject( inData );
		getMobileNumber();
		
		var myURL = connectionSettingController.getConnection_URL();
		myURL = myURL + "/" + methodName.replace("/","");
	
		cordovaHTTP.postJson(
			myURL, 
			obData, 
			{}, 
			function(res){ 
				console.log(" [ " + methodName + " ] ----> SUCCESS");
				 try {
					 res.data = JSON.parse(res.data);
				 
				        console.log(res.data.message);
				        callBack_Success(res.data);
				    } catch(e) {
				        console.error("JSON parsing error");
				    }
			}, 
			function(res){ 
				console.log(" [ " + methodName + " ] ----> FAILURE");
				console.log(res.status);
				
		    console.log(res.error);
			    
				callBack_Error(res);
			}
		);
		
	};
```

Method POST_WITHOUT_PINNING is working correctly, or variables are setup the same way for both methods. 

var myUrl is proper link
var obData is json string object
callback methods for success / fail are provided

**Comment by brendonparker** [comment]
I believe it is expecting a javascript object, not a json string (for your
obData).

**Comment by Remicek** [comment]
Oh... ok i get this working but i had to override plugin to accept all certs 

```
window.cordovaHTTP.acceptAllCerts(
			    true,
			    function(res) {console.log('Accept all certs: ' + res)},
			    function(err) {console.log('Accept all certs: ' + err)}
			);
```

so there may be something wrong with the cert i am using, if i dont acceptAllCerts i get:
"There was an error with the request".

Thanks for your help :)

**Comment by apparition47** [comment]
I ported over your fork based on [1.0.2](https://github.com/Switch168/cordova-HTTP).

**Comment by AlexChesser** [comment]
Any chance of getting this merged in @wymsee-codeship @TheKiteEatingTree?  would be really nice to have this folded back into the master branch.

**Comment by rusheeljain** [comment]
Hi Brendon

I am trying to make use of your version of the plugin, but I am always getting the error of "cordovaHTTP.postJson" is not a function.

Steps:
Using Evothings Workbench for ios. Added the plugin to my cordova project via 
cordova plugin add https://github.com/brendonparker/cordova-HTTP.git

Then I simply copy pasted your postJSON example in a method is called as soon as device is ready.

Could you please guide me where I might be doing wrong.
Thanks

**Comment by brendonparker** [comment]
Hmm. `cordovaHTTP.postJson` should be a function. Have you tried deleting
your platforms and re-adding them? I wonder if something is cached?

**Comment by dukhanov** [comment]
Hi Brendon

It does not work with cordova iOS 4.1.1
image

**Comment by apparition47** [comment]
Try my fork of Brendon's fork https://github.com/Switch168/cordova-HTTP

**Comment by dukhanov** [comment]
Thanks @apparition47,
I changed method `post` as in yours fork, now it works.

@brendonparker could you please fix it?

**Comment by apparition47** [comment]
@brendonparker I noticed recently that when I try to `cordovaHTTP.postJson()` an array `[]` in Android, I get a `JSON error`. It works fine in iOS, however. Any ideas?

**Comment by dpakthakur** [comment]
@brendonparker if I post array of objects, i get json error in error 403 block. My json looks like 
[{ "a": "valA", "b": "valB"}, { "x": "valX", "y": "valY"}]. How do I post this as a body / data to url?

**Comment by brendonparker** [comment]
Closing this as it is super stale.
